#!/usr/bin/python

import gitSOC
import argparse
import gitSOC.cmd.register
import gitSOC.cmd.status
import gitSOC.cmd.info
import gitSOC.cmd.fetch
import gitSOC.cmd.pull
import gitSOC.cmd.push
import gitSOC.cmd.pushpull
import gitSOC.cmd.interactive
import gitSOC.cmd.cmd
import sys

soc = gitSOC.GitSOC()
baseargs = soc.parse_global_args()

args = sys.argv

# pull off the real command
cmd = args[1]

# drop the exec file and the command name
args = args[2:]

if cmd == 'register':
    cmd = gitSOC.cmd.register.Register(soc, baseargs = baseargs)
elif cmd == 'status':
    cmd = gitSOC.cmd.status.Status(soc, baseargs = baseargs)
elif cmd == 'info':
    cmd = gitSOC.cmd.info.Info(soc, baseargs = baseargs)
elif cmd == 'pull':
    cmd = gitSOC.cmd.pull.Pull(soc, baseargs = baseargs)
elif cmd == 'fetch':
    cmd = gitSOC.cmd.fetch.Fetch(soc, baseargs = baseargs)
elif cmd == 'push':
    cmd = gitSOC.cmd.push.Push(soc, baseargs = baseargs)
elif cmd == 'pushpull' or cmd == "pp":
    cmd = gitSOC.cmd.pushpull.PushPull(soc, baseargs = baseargs)
elif cmd == 'command' or cmd == "cmd":
    cmd = gitSOC.cmd.cmd.Cmd(soc, baseargs = baseargs)
elif cmd == 'diff':
    cmd = gitSOC.cmd.cmd.Cmd(soc, baseargs = baseargs)
    args = ["git diff"]
elif cmd == 'interactive':
    cmd = gitSOC.cmd.interactive.Interactive(soc, baseargs = baseargs)
elif cmd == 'git':
    cmd = gitSOC.cmd.cmd.Cmd(soc, baseargs = baseargs)
    args[0] = "git " + args[0]
elif cmd == "-h" or cmd == "--help" or cmd == "help":
    print("Usage: " + sys.argv[0] + " COMMAND [-B basedir] <COMMAND ARGS>")
    print("Commands available:")
    print("    " + "\n    ".join(["register","info","status","pull","push","pushpull","command"]))
    print("\nSee the --help output of each command for further details")
    exit(0)
else:
    print("unknown command: " + cmd)
    exit(1)
    
parsed_args = cmd.parse_args(args)
soc.load_config_directory(parsed_args.base, cmd)
cmd.run(parsed_args)

